const APP={propertyKey:'INTEGRATED_APP_CONFIG',headers:{Members:['MemberId','Email','Name','Faculty','Grade','Department','GraduateSchool','Major','Gender','LineName','PreviousMember','JoinedAt','Active'],MembershipYears:['MembershipId','MemberId','FiscalYear','JoinedAt','FeeAmount','ReceiptId','Active'],Receipts:['ReceiptId','IssuedAt','IssuedBy','Email','Name','Amount','Description','FiscalYear'],Events:['EventId','Status','Published','Genre','Subtype','Title','ExhibitionTitle','StartAt','EndAt','Place','Contact','Details','Fee','PaymentDeadline','MaxWorks','CameraEnabled','DisposableEnabled','ShiftSlotsJson','MinShiftPeople','CreatedAt','UpdatedAt','UpdatedBy'],Responses:['ResponseId','SubmittedAt','EventId','Email','Name','LineName','Attendance','Camera','DisposableCamera','Allergies','OtherAllergy','Note','Agreement','PaymentStatus','CancelledAt'],Exhibits:['EventId','Email','WorkNo','Title','Description','ImageUrl','Feedback'],Shifts:['EventId','SlotId','SlotLabel','Email','Name','Status'],Admins:['Email','Name','Active'],ParticipantSheets:['EventId','SheetName','Title','Genre','UpdatedAt'],ParticipantView:['ResponseId','SubmittedAt','MemberId','Name','Faculty','Grade','Department','GraduateSchool','Major','Gender','LineName','Attendance','Camera','DisposableCamera','Allergies','OtherAllergy','Note','Agreement','PaymentStatus','CancelledAt']}};

function doGet(e){const p=e&&e.parameter||{},file=p.page==='admin'?'Admin':p.page==='form'&&p.event?'Form':'index',t=HtmlService.createTemplateFromFile(file);t.eventId=String(p.event||'');t.webAppUrl=url_();return t.evaluate().setTitle('法政大学写真研究会 活動ポータル').addMetaTag('viewport','width=device-width, initial-scale=1')}
function include(n){return HtmlService.createHtmlOutputFromFile(n).getContent()}

/** 幹部アカウントで最初に一度だけ実行する。 */
function setupIntegratedApp(){const ps=PropertiesService.getScriptProperties();if(ps.getProperty(APP.propertyKey))throw new Error('セットアップ済みです。');const root=DriveApp.createFolder('写真研究会 統合Webアプリ'),db=root.createFolder('DB'),settings=root.createFolder('Settings'),books={};[['memberDb','領収証・部員名簿 記録ブック',db,['Members','MembershipYears','Receipts']],['meetingDb','全体会 記録ブック',db,['Responses']],['campDb','合宿 記録ブック',db,['Responses']],['exhibitionDb','写真展 記録ブック',db,['Responses','Exhibits','Shifts']],['participantViewDb','行事参加者 閲覧ブック',db,['ParticipantSheets']],['settingsDb','統合アプリ 設定ブック',settings,['Events','Admins']]].forEach(d=>{const ss=SpreadsheetApp.create(d[1]);DriveApp.getFileById(ss.getId()).moveTo(d[2]);d[3].forEach((name,i)=>{const s=i?ss.insertSheet():ss.getSheets()[0];s.setName(name);s.getRange(1,1,1,APP.headers[name].length).setValues([APP.headers[name]]).setFontWeight('bold');s.setFrozenRows(1)});books[d[0]]=ss.getId()});SpreadsheetApp.openById(books.settingsDb).getSheetByName('Admins').appendRow([email_(),'初期管理者',true]);const config={rootFolderId:root.getId(),dbFolderId:db.getId(),settingsFolderId:settings.getId(),books};ps.setProperty(APP.propertyKey,JSON.stringify(config));installDailyTrigger_();return config}

/** セットアップ済み環境へ年度在籍シートを追加する。1回実行すればよい。 */
function initializeMembershipYears(){const s=ensureMembershipYearsSheet_();return{ok:true,spreadsheetUrl:openBook_('memberDb').getUrl(),sheetName:s.getName(),message:'MembershipYearsシートを準備しました。'}}

function getPortalData(token){const email=authenticate_(token).email,events=objects_(sheet_('settingsDb','Events')).filter(e=>bool_(e.Published)&&String(e.Status).trim()==='saved').sort((a,b)=>new Date(a.StartAt)-new Date(b.StartAt)),member=findMember_(email),membership=member?findMembership_(member.MemberId,currentFiscalYear_()):null,responses=getMemberEventResponses_(email,events);return{email,member:publicMember_(member,membership),isAdmin:isAdmin_(email),webAppUrl:url_(),events:events.map(function(event){const item=publicEvent_(event);item.response=responses[String(event.EventId)]||null;return item;}),photo:getMemberExhibitionArchives_(email)}}
function getEventFormData(token,id){const email=authenticate_(token).email,event=findEvent_(id),member=findMember_(email),membership=member?findMembership_(member.MemberId,currentFiscalYear_()):null;if(!event||!bool_(event.Published)||String(event.Status).trim()!=='saved')throw new Error('この予定は現在公開されていません。');if(!member)throw new Error('部員名簿に登録されていません。幹部へお問い合わせください。');if(!membership)throw new Error(currentFiscalYear_()+'年度の在籍登録がありません。部費支払い後、幹部へお問い合わせください。');return{event:publicEvent_(event),member:publicMember_(member,membership),existingResponse:getMemberEventResponse_(email,event),cameraRemaining:Math.max(0,3-cameraCount_(id)),webAppUrl:url_()}}
function submitEventResponse(token,p){p=p||{};const email=authenticate_(token).email,event=findEvent_(p.eventId),member=findMember_(email),membership=member?findMembership_(member.MemberId,currentFiscalYear_()):null,attendance=String(p.attendance||'').trim();if(!event||!bool_(event.Published)||String(event.Status).trim()!=='saved')throw new Error('受付は終了しています。');if(!member)throw new Error('部員名簿に登録されていません。');if(!membership)throw new Error(currentFiscalYear_()+'年度の在籍登録がありません。');if(!['参加','不参加'].includes(attendance))throw new Error('参加・不参加を選択してください。');if(attendance==='参加'&&event.Genre==='camp'&&!bool_(p.agreement))throw new Error('取消条件と支払期限への同意が必要です。');if(attendance==='参加'&&(event.Genre==='camp'||event.Subtype==='dining')&&!String(p.allergies||'').trim())throw new Error('アレルギー情報を入力してください。');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const target=responseSheet_(event.Genre);if(objects_(target).some(r=>String(r.EventId).trim()===String(event.EventId).trim()&&String(r.Email).toLowerCase()===email&&!r.CancelledAt))throw new Error('この予定には回答済みです。回答内容は部員画面で確認できます。');if(attendance==='参加'&&bool_(p.camera)&&bool_(event.CameraEnabled)&&cameraCount_(event.EventId)>=3)throw new Error('貸出カメラは上限3台に達しました。');target.appendRow([Utilities.getUuid(),new Date(),event.EventId,email,member.Name,String(p.lineName||member.LineName||'').slice(0,100),attendance,attendance==='参加'&&bool_(p.camera),attendance==='参加'&&bool_(p.disposableCamera),attendance==='参加'?String(p.allergies||''):'',attendance==='参加'?String(p.otherAllergy||''):'',String(p.note||'').slice(0,1000),attendance==='参加'&&bool_(p.agreement),attendance==='参加'&&num_(event.Fee)>0?'unpaid':'not_required','']);try{syncParticipantViewerSheet_(event.EventId)}catch(syncError){console.error(syncError)}return{ok:true,message:'回答を受け付けました。'}}finally{lock.releaseLock()}}

function getAdminData(token){assertAdmin_(token);const events=objects_(sheet_('settingsDb','Events')).sort((a,b)=>new Date(b.UpdatedAt)-new Date(a.UpdatedAt)).map(clientSafeObject_),participantBookId=config_().books.participantViewDb||'';return{events:events,archiveExhibitions:getArchiveAdminSummary_(),webAppUrl:url_(),participantViewerUrl:participantBookId?'https://docs.google.com/spreadsheets/d/'+participantBookId+'/edit':''}}
function saveEvent(token,p,draft){const user=assertAdmin_(token);p=p||{};validateEvent_(p,!draft);const s=sheet_('settingsDb','Events'),v=s.getDataRange().getValues(),now=new Date(),id=String(p.eventId||Utilities.getUuid()),record=[id,draft?'draft':'saved',false,String(p.genre),String(p.subtype||''),String(p.title||''),String(p.exhibitionTitle||''),date_(p.startAt),date_(p.endAt),String(p.place||''),String(p.contact||''),String(p.details||''),num_(p.fee),date_(p.paymentDeadline),num_(p.maxWorks),bool_(p.cameraEnabled),bool_(p.disposableEnabled),JSON.stringify(p.shiftSlots||[]),num_(p.minShiftPeople),p.createdAt?date_(p.createdAt):now,now,user];let row=0;for(let i=1;i<v.length;i++)if(String(v[i][0])===id){row=i+1;record[2]=v[i][2];break}if(row)s.getRange(row,1,1,record.length).setValues([record]);else s.appendRow(record);ensureParticipantEventSheet_(id);return{ok:true,eventId:id,message:draft?'下書きを保存しました。':'予定を保存しました。公開設定は変更していません。'}}
function setEventPublished(token,id,published){const user=assertAdmin_(token),s=sheet_('settingsDb','Events'),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0]).trim()===String(id).trim()){if(bool_(published)&&String(v[i][1]).trim()!=='saved')throw new Error('下書きは公開できません。');s.getRange(i+1,3).setValue(bool_(published));s.getRange(i+1,21,1,2).setValues([[new Date(),user]]);SpreadsheetApp.flush();return{ok:true,published:bool_(published)}}throw new Error('予定が見つかりません。')}
function deleteEvent(token,id){assertAdmin_(token);const s=sheet_('settingsDb','Events'),values=s.getDataRange().getValues(),target=String(id||'').trim();for(let row=1;row<values.length;row++)if(String(values[row][0]||'').trim()===target){deleteParticipantEventSheet_(target);s.deleteRow(row+1);return{ok:true,message:'予定と参加者閲覧シートを削除しました。回答台帳は保存されています。'}}throw new Error('削除する予定が見つかりません。')}
function issueMembershipReceipt(token,p){const issuer=assertAdmin_(token);['email','name','faculty','grade'].forEach(k=>{if(!String(p[k]||'').trim())throw new Error('必須項目を入力してください。')});const year=Number(p.fiscalYear)||currentFiscalYear_(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const memberSheet=sheet_('memberDb','Members'),membershipSheet=ensureMembershipYearsSheet_(),email=String(p.email).trim().toLowerCase(),members=objects_(memberSheet);let member=members.find(m=>String(m.Email).trim().toLowerCase()===email);if(member&&objects_(membershipSheet).some(m=>String(m.MemberId)===String(member.MemberId)&&Number(m.FiscalYear)===year))throw new Error(year+'年度の在籍登録と領収証発行は完了しています。');const now=new Date();if(member){const row=members.indexOf(member)+2;memberSheet.getRange(row,2,1,12).setValues([[email,p.name,p.faculty,p.grade,p.department||'',p.graduateSchool||'',p.major||'',p.gender||'',p.lineName||'',p.previousMember||'',member.JoinedAt||now,true]]);}else{member={MemberId:nextMemberId_(members)};memberSheet.appendRow([member.MemberId,email,p.name,p.faculty,p.grade,p.department||'',p.graduateSchool||'',p.major||'',p.gender||'',p.lineName||'',p.previousMember||'',now,true]);}const receiptId=Utilities.getUuid(),membershipId='membership-'+year+'-'+String(member.MemberId).replace(/^member-/,'');sheet_('memberDb','Receipts').appendRow([receiptId,now,issuer,email,p.name,num_(p.amount),year+'年度部費として',year]);membershipSheet.appendRow([membershipId,member.MemberId,year,now,num_(p.amount),receiptId,true]);return{ok:true,memberId:member.MemberId,membershipId:membershipId,receiptId:receiptId,description:year+'年度部費として',message:year+'年度の在籍登録と領収証記録を保存しました。'}}finally{lock.releaseLock()}}

function cancelOverdueCampResponses(){const deadlines={};objects_(sheet_('settingsDb','Events')).forEach(e=>{if(e.Genre==='camp'&&e.PaymentDeadline)deadlines[e.EventId]=new Date(e.PaymentDeadline)});const s=sheet_('campDb','Responses'),v=s.getDataRange().getValues(),now=new Date(),rows=[];for(let i=1;i<v.length;i++)if(deadlines[v[i][2]]&&deadlines[v[i][2]]<now&&v[i][13]==='unpaid'&&!v[i][14])rows.push(i+1);rows.forEach(r=>s.getRange(r,14,1,2).setValues([['cancelled',now]]));[...new Set(rows.map(r=>String(v[r-1][2])))].forEach(id=>{try{syncParticipantViewerSheet_(id)}catch(error){console.error(error)}});return rows.length}
function installDailyTrigger_(){if(!ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==='cancelOverdueCampResponses'))ScriptApp.newTrigger('cancelOverdueCampResponses').timeBased().everyDays(1).atHour(1).create()}

/** Google Cloudを使わず、対象メールアドレスへ6桁コードを送信する。 */
function requestEmailLogin(rawEmail){const email=String(rawEmail||'').trim().toLowerCase();if(!/^[-+.\w]+@[-.\w]+$/.test(email))throw new Error('メールアドレスを正しく入力してください。');if(!email.endsWith('@stu.hosei.ac.jp')&&!isAdmin_(email))throw new Error('このメールアドレスは対象ではありません。大学メールまたは登録済み幹部メールを入力してください。');const cache=CacheService.getScriptCache(),key=authKey_(email),rateKey='login_rate:'+key;if(cache.get(rateKey))throw new Error('確認コードは送信済みです。1分ほど待ってから再送してください。');const code=String(Math.floor(100000+Math.random()*900000));cache.put('login_code:'+key,code,600);cache.put('login_attempts:'+key,'0',600);cache.put(rateKey,'1',60);MailApp.sendEmail({to:email,subject:'【法政大学写真研究会】ログイン確認コード',body:'統合活動ポータルのログイン確認コードは '+code+' です。\n\n有効期限は10分です。心当たりがない場合は、このメールを破棄してください。',name:'法政大学写真研究会'});return{ok:true,masked:maskEmail_(email),message:'確認コードを送信しました。'}}
function verifyEmailLogin(rawEmail,rawCode){const email=String(rawEmail||'').trim().toLowerCase(),code=String(rawCode||'').trim(),cache=CacheService.getScriptCache(),key=authKey_(email),saved=cache.get('login_code:'+key),attempts=Number(cache.get('login_attempts:'+key)||0);if(attempts>=5)throw new Error('入力回数の上限に達しました。新しいコードを発行してください。');if(!saved){throw new Error('確認コードの有効期限が切れました。新しいコードを発行してください。')}if(saved!==code){cache.put('login_attempts:'+key,String(attempts+1),600);throw new Error('確認コードが一致しません。')}cache.remove('login_code:'+key);cache.remove('login_attempts:'+key);const session=Utilities.getUuid()+Utilities.getUuid(),user={email,name:''};cache.put('app_session:'+session,JSON.stringify(user),21600);return{session,email,isAdmin:isAdmin_(email)}}
function getAuthContext(token){const user=authenticate_(token);return{email:user.email,name:user.name||'',isAdmin:isAdmin_(user.email)}}
function authenticate_(token){token=String(token||'').trim();if(!token)throw new Error('AUTH_REQUIRED: メール認証を行ってください。');const cached=CacheService.getScriptCache().get('app_session:'+token);if(!cached)throw new Error('AUTH_EXPIRED: ログインの有効期限が切れました。もう一度認証してください。');return JSON.parse(cached)}
function authKey_(email){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(email))).slice(0,60)}
function maskEmail_(email){const parts=email.split('@'),name=parts[0];return(name.length<=2?name[0]+'*':name.slice(0,2)+'***'+name.slice(-1))+'@'+parts[1]}
function validateEvent_(p,complete){if(!String(p.title||'').trim())throw new Error('予定名は必須です。');if(!['meeting','camp','exhibition'].includes(p.genre))throw new Error('ジャンルを選択してください。');if(p.genre==='meeting'&&!['shooting','dining'].includes(p.subtype))throw new Error('全体会の種別を選択してください。');if(!complete)return;if(!p.startAt||!p.place||!p.contact)throw new Error('日時・場所・連絡先は必須です。');if(p.genre==='camp'&&(!num_(p.fee)||!p.paymentDeadline))throw new Error('合宿では費用と支払期限が必須です。');if(p.genre==='exhibition'&&(!p.exhibitionTitle||!num_(p.maxWorks)||!(p.shiftSlots||[]).length||!num_(p.minShiftPeople)))throw new Error('写真展タイトル・作品数・シフト枠・最低人数は必須です。')}
function photo_(email,events){const ids=events.filter(e=>e.Genre==='exhibition').map(e=>e.EventId);if(!ids.length)return[];const works=objects_(sheet_('exhibitionDb','Exhibits')).filter(x=>ids.includes(x.EventId)&&String(x.Email).toLowerCase()===email),shifts=objects_(sheet_('exhibitionDb','Shifts')).filter(x=>ids.includes(x.EventId)&&String(x.Email).toLowerCase()===email);return ids.map(id=>({eventId:id,works:works.filter(x=>x.EventId===id),shifts:shifts.filter(x=>x.EventId===id)})).filter(x=>x.works.length||x.shifts.length)}
function responseSheet_(g){return g==='camp'?sheet_('campDb','Responses'):g==='exhibition'?sheet_('exhibitionDb','Responses'):sheet_('meetingDb','Responses')}
function getMemberEventResponses_(email,events){const result={},genres={};(events||[]).forEach(function(event){genres[event.Genre]=true;});Object.keys(genres).forEach(function(genre){objects_(responseSheet_(genre)).forEach(function(response){if(String(response.Email||'').trim().toLowerCase()===email)result[String(response.EventId)]=publicResponse_(response);});});return result}
function getMemberEventResponse_(email,event){return getMemberEventResponses_(email,[event])[String(event.EventId)]||null}
function publicResponse_(response){return{responseId:String(response.ResponseId||''),submittedAt:clientSafeValue_(response.SubmittedAt),attendance:String(response.Attendance||''),lineName:String(response.LineName||''),camera:bool_(response.Camera),disposableCamera:bool_(response.DisposableCamera),allergies:String(response.Allergies||''),otherAllergy:String(response.OtherAllergy||''),note:String(response.Note||''),agreement:bool_(response.Agreement),paymentStatus:String(response.PaymentStatus||''),cancelledAt:clientSafeValue_(response.CancelledAt)}}
function cameraCount_(id){return objects_(sheet_('meetingDb','Responses')).filter(r=>r.EventId===id&&bool_(r.Camera)&&!r.CancelledAt).length}
function findEvent_(id){const target=String(id||'').trim();return objects_(sheet_('settingsDb','Events')).find(e=>String(e.EventId||'').trim()===target)}
function findMember_(email){return objects_(sheet_('memberDb','Members')).find(m=>String(m.Email).toLowerCase()===email&&bool_(m.Active))}
function ensureMembershipYearsSheet_(){const ss=openBook_('memberDb');let s=ss.getSheetByName('MembershipYears');if(!s){s=ss.insertSheet('MembershipYears');s.getRange(1,1,1,APP.headers.MembershipYears.length).setValues([APP.headers.MembershipYears]).setFontWeight('bold');s.setFrozenRows(1)}return s}
function findMembership_(memberId,fiscalYear){return objects_(ensureMembershipYearsSheet_()).find(m=>String(m.MemberId)===String(memberId)&&Number(m.FiscalYear)===Number(fiscalYear)&&bool_(m.Active))||null}
function nextMemberId_(members){let max=0;(members||[]).forEach(m=>{const match=String(m.MemberId||'').match(/^member-(\d+)$/);if(match)max=Math.max(max,Number(match[1]))});return'member-'+String(max+1).padStart(4,'0')}
function currentFiscalYear_(){const now=new Date(),month=Number(Utilities.formatDate(now,Session.getScriptTimeZone(),'M'));return Number(Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy'))-(month<4?1:0)}
function publicMember_(m,membership){return m?{memberId:m.MemberId,email:m.Email,name:m.Name,faculty:m.Faculty,grade:m.Grade,department:m.Department,graduateSchool:m.GraduateSchool,major:m.Major,lineName:m.LineName,membership:membership?{fiscalYear:Number(membership.FiscalYear),joinedAt:clientSafeValue_(membership.JoinedAt),feeAmount:Number(membership.FeeAmount||0),active:bool_(membership.Active)}:null,currentFiscalYear:currentFiscalYear_()}:null}
function publicEvent_(e){return{id:e.EventId,genre:e.Genre,subtype:e.Subtype,title:e.Title,exhibitionTitle:e.ExhibitionTitle,startAt:clientSafeValue_(e.StartAt),endAt:clientSafeValue_(e.EndAt),place:e.Place,contact:e.Contact,details:e.Details,fee:e.Fee,paymentDeadline:clientSafeValue_(e.PaymentDeadline),maxWorks:e.MaxWorks,cameraEnabled:bool_(e.CameraEnabled),disposableEnabled:bool_(e.DisposableEnabled),shiftSlots:json_(e.ShiftSlotsJson,[]),minShiftPeople:e.MinShiftPeople}}
let runtimeConfigCache_=null,runtimeBookCache_={};
function config_(){if(runtimeConfigCache_)return runtimeConfigCache_;const r=PropertiesService.getScriptProperties().getProperty(APP.propertyKey);if(!r)throw new Error('初期設定がありません。setupIntegratedApp を実行してください。');runtimeConfigCache_=JSON.parse(r);return runtimeConfigCache_}
function openBook_(book){if(!runtimeBookCache_[book])runtimeBookCache_[book]=SpreadsheetApp.openById(config_().books[book]);return runtimeBookCache_[book]}
function sheet_(book,name){return openBook_(book).getSheetByName(name)}
function objects_(s){const v=s.getDataRange().getValues();if(v.length<2)return[];return v.slice(1).filter(r=>r.some(x=>x!=='')).map(r=>{const o={};v[0].forEach((h,i)=>o[h]=r[i]);return o})}
function isAdmin_(email){if(!email)return false;try{return objects_(sheet_('settingsDb','Admins')).some(a=>String(a.Email).toLowerCase()===email&&bool_(a.Active))}catch(e){return false}}
function assertAdmin_(token){const e=authenticate_(token).email;if(!isAdmin_(e))throw new Error('管理者権限がありません。');return e}
function email_(){return String(Session.getActiveUser().getEmail()||'').trim().toLowerCase()}
function url_(){return String(ScriptApp.getService().getUrl()||'').replace(/^https:\/\/script\.google\.com\/a\/macros\/[^/]+\/s\//,'https://script.google.com/macros/s/')}
function bool_(v){return v===true||['true','1','yes','on','参加'].includes(String(v||'').toLowerCase())}function num_(v){const n=Number(v);return isFinite(n)?n:0}function date_(v){return v?new Date(v):''}function json_(v,f){try{return JSON.parse(String(v||''))}catch(e){return f}}
function clientSafeValue_(value){return value instanceof Date?Utilities.formatDate(value,Session.getScriptTimeZone(),"yyyy-MM-dd'T'HH:mm:ssXXX"):value}
function clientSafeObject_(object){const out={};Object.keys(object||{}).forEach(function(key){out[key]=clientSafeValue_(object[key]);});return out}
